apiVersion: v1
kind: Service
metadata:
  name: myapp-mysql
  labels:
    app: myapp-mysql
spec: 
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
      app: myapp-mysql
