apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtualization-mysql-pv-claim
spec:
  storageClassName: local-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
