apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-mysql
  labels:
    app: myapp-mysql  
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: myapp-mysql
  template:
    metadata:
      labels:
        app: myapp-mysql         
    spec:
      containers:
      - name: mysql-database-container
        image: n01551957/mysql_db:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: Virtualization_project
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
        - name: virtualization-project-volume
          mountPath: /var/lib/mysql
      volumes:
        - name: virtualization-project-volume
          persistentVolumeClaim:
            claimName: virtualization-mysql-pv-claim
