apiVersion: v1
kind: PersistentVolume
metadata:
  name: virtualization-mysql-pv
spec:
  storageClassName: local-pv
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
