apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec: 
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  selector:
      app: myapp 
