apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtualization_mysql_pv_claim
spec:
  storageClassName: local-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
